Desmos updated to 0.7
in2workspace/helm-charts pull request #62
Opened 2024-06-14 14:11 UTC by yaniaiciin2

2024-06-14 15:03 UTC, oriolcanades requested changes

2024-06-14 15:03 UTC, oriolcanades commented on charts/desmos/Chart.yaml
> +appVersion: v0.8.0
L'App version hauria se ser la v0.7.0 perquè fa referència a la sol·lució

2024-06-14 15:03 UTC, oriolcanades commented on charts/desmos/values.yaml
> +  tag: v0.7.0-SNAPSHOT
Si hem provat que va bé. Faig la v0.7.0 i no fem servir la SNAPSHOT

2024-06-14 15:57 UTC, yaniaiciin2 commented on charts/desmos/values.yaml
> +  tag: v0.7.0-SNAPSHOT
Tens les evidències al Jira

2024-06-17 06:36 UTC, oriolcanades approved these changes

2024-06-17 06:36 UTC, merged